services:
  runner:
    image: heindetotverre/actions-runner:latest
    restart: unless-stopped
    environment:
      - REPO=heindetotverre/momo
      - TOKEN=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
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4000M
        reservations:
          cpus: '.5'
          memory: 500M