name: MoMo Pipeline
run-name: Run tests and publish MoMo
on: [push]
jobs:
  MoMoPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: echo 'run unit tests'
      - name: echo 'run e2e tests'
      - name: echo 'run lighthouse test'
      - name: echo 'publish'
      - run: git push dokku master
      - run: echo 'this job's status is ${{ job.status }}'