name: Momo deploy
on: workflow_dispatch
jobs: 
  firstjob: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: | 
          echo "Hello world"
          echo "Done - bye!"
        
