name: Momo deploy
on: 
  push: 
    branches: 
      - master
jobs: 
  deploy: 
    runs-on: [self-hosted, pi]
    steps: 
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          architecture: 'x64'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
        
